apiVersion: v1
kind: Service
metadata:
  name: object-detection-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: object-detection