name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and build React frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for microservices
        run: |
          pip install -r notifier/requirements.txt
          pip install -r "object detection"/requirements.txt
          pip install -r storage/requirements.txt

      - name: Build frontend Docker image
        run: docker build -t cloud-hf/frontend:latest ./frontend

      - name: Push frontend Docker image
        run: docker push cloud-hf/frontend

      - name: Build notifier Docker image
        run: docker build -t cloud-hf/notifier:latest ./notifier

      - name: Push notifier Docker image
        run: docker push cloud-hf/notifier

      - name: Build object detection Docker image
        run: docker build -t cloud-hf/object-detection:latest "./object detection"

      - name: Push object detection Docker image
        run: docker push cloud-hf/object-detection

      - name: Build storage Docker image
        run: docker build -t cloud-hf/storage:latest ./storage

      - name: Push storage Docker image
        run: docker push cloud-hf/storag
